#line 2 "scanner.yy.c"

#line 4 "scanner.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 71
#define YY_END_OF_BUFFER 72
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[143] =
    {   0,
        0,    0,    0,    0,    0,    0,   72,   70,    1,    2,
       59,    9,    3,   56,   70,   64,   65,   54,   52,   61,
       53,   63,   55,   42,   62,   60,   57,   51,   58,   43,
       68,   69,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   66,   70,   67,    8,
        7,    8,   10,   14,   13,   71,    1,   46,    3,   49,
       39,    5,    4,   40,   42,   44,   47,   45,   48,   43,
       43,   43,   43,   21,   43,   43,   43,   43,   43,   17,
       43,   43,   36,   43,   43,   43,   43,   32,   43,   43,
       43,   50,    6,   10,   12,   11,    4,    0,   41,   35,

       43,   43,   43,   16,   43,   43,   20,   24,   37,   43,
       43,   43,   43,   43,   43,   43,   29,   43,   38,   43,
       27,   18,   43,   43,   43,   23,   43,   31,   43,   30,
       33,   43,   15,   34,   25,   22,   43,   43,   19,   28,
       26,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,    1,    1,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       24,   25,   26,    1,   23,    1,   27,   28,   23,   29,

       30,   31,   32,   33,   34,   23,   23,   35,   23,   36,
       37,   38,   23,   39,   40,   41,   42,   43,   44,   23,
       23,   23,   45,   46,   47,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[48] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    4,    1,    1,    1,
        1,    1,    4,    1,    3,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    1
    } ;

static const flex_int16_t yy_base[150] =
    {   0,
        0,    0,   45,   46,   47,   48,  167,  168,  164,  168,
      144,  168,    0,  168,  156,  168,  168,  168,  168,  168,
      168,  146,   43,   43,  141,  168,  140,  139,  138,    0,
      168,  168,  122,   25,  120,   28,   34,   34,  119,  116,
      115,  123,  111,   41,  124,  117,  168,  103,  168,  168,
      168,  132,    0,  168,  168,   61,  145,  168,    0,  168,
      129,  168,    0,   60,   64,  168,  168,  168,  168,    0,
      116,  112,  106,    0,  102,  112,  105,  102,   99,    0,
       96,   95,    0,  101,   41,   37,  104,    0,   91,   93,
       97,  168,  168,    0,  168,  168,    0,  113,  112,    0,

       94,   92,   94,    0,   80,   90,    0,    0,    0,   80,
       83,   59,   62,   65,   62,   66,    0,   60,   77,   57,
        0,    0,   62,   50,   49,    0,   50,    0,   52,    0,
        0,   57,    0,    0,    0,    0,   49,   52,    0,    0,
        0,  168,  102,  106,  110,   79,  114,  118,  122
    } ;

static const flex_int16_t yy_def[150] =
    {   0,
      142,    1,  143,  143,  144,  144,  142,  142,  142,  142,
      142,  142,  145,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  146,
      142,  142,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  142,  142,  142,  142,
      142,  142,  147,  142,  142,  148,  142,  142,  145,  142,
      142,  142,  149,  142,  142,  142,  142,  142,  142,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  142,  142,  147,  142,  142,  149,  142,  142,  146,

      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  142,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,    0,  142,  142,  142,  142,  142,  142,  142
    } ;

static const flex_int16_t yy_nxt[216] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,    8,   32,   33,   34,   35,   36,
       37,   30,   30,   38,   30,   39,   40,   41,   42,   43,
       44,   30,   45,   46,   47,   48,   49,   51,   51,   54,
       54,   55,   55,   62,   72,   52,   52,   64,   63,   65,
       77,   73,   75,   76,   80,   96,  113,  111,   78,   81,
       79,   56,   56,   87,   98,  114,   99,   88,   64,   89,
       65,  112,   70,  141,  140,   96,  139,  138,  137,  136,
      135,  134,  133,  119,  132,  131,   96,  130,  129,  128,

      127,   96,   50,   50,   50,   50,   53,   53,   53,   53,
       59,  126,   59,   59,   94,  125,  124,   94,   95,  123,
       95,   95,   97,  122,   97,   97,  121,  120,   99,  119,
      118,  117,  116,  115,  110,  109,  108,  107,  106,  105,
      104,  103,  102,  101,  100,   61,   57,   93,   92,   91,
       90,   86,   85,   84,   83,   82,   74,   71,   69,   68,
       67,   66,   61,   60,   58,   57,  142,    7,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,

      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142
    } ;

static const flex_int16_t yy_chk[216] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    5,
        6,    5,    6,   23,   34,    3,    4,   24,   23,   24,
       37,   34,   36,   36,   38,   56,   86,   85,   37,   38,
       37,    5,    6,   44,   64,   86,   64,   44,   65,   44,
       65,   85,  146,  138,  137,   56,  132,  129,  127,  125,
      124,  123,  120,  119,  118,  116,   56,  115,  114,  113,

      112,   56,  143,  143,  143,  143,  144,  144,  144,  144,
      145,  111,  145,  145,  147,  110,  106,  147,  148,  105,
      148,  148,  149,  103,  149,  149,  102,  101,   99,   98,
       91,   90,   89,   87,   84,   82,   81,   79,   78,   77,
       76,   75,   73,   72,   71,   61,   57,   52,   48,   46,
       45,   43,   42,   41,   40,   39,   35,   33,   29,   28,
       27,   25,   22,   15,   11,    9,    7,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,

      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#define YY_NO_INPUT 1


#line 7 "scanner.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

#include "parser.tab.h"

static int current_line = 1;
static int current_col = 1;
static int token_index = 0;
static int token_line = 1;
static int token_col = 1;

typedef struct {
    int number;
    int line;
    char *lexeme;
    char *type_name;
    char *value;
} token_row_t;

static token_row_t *table_rows = NULL;
static size_t table_rows_count = 0;
static size_t table_rows_cap = 0;

static int comment_start_line = 1;
static int comment_start_col = 1;

static int string_start_line = 1;
static int string_start_col = 1;

static char string_lexeme[8192];
static char string_value[8192];
static int string_lexeme_len = 0;
static int string_value_len = 0;

static void mark_token_start(void) {
    token_line = current_line;
    token_col = current_col;
}

static void advance_position_text(const char *text, int len) {
    int i = 0;
    while (i < len) {
        if (text[i] == '\n') {
            current_line += 1;
            current_col = 1;
        } else {
            current_col += 1;
        }
        i += 1;
    }
}

static void print_escaped(FILE *out, const char *s) {
    size_t i = 0;
    while (s[i] != '\0') {
        unsigned char c = (unsigned char)s[i];
        if (c == '\n') {
            fputs("\\n", out);
        } else if (c == '\t') {
            fputs("\\t", out);
        } else if (c == '\r') {
            fputs("\\r", out);
        } else if (c == '\\') {
            fputs("\\\\", out);
        } else if (c == '"') {
            fputs("\\\"", out);
        } else if (c < 32 || c == 127) {
            fprintf(out, "\\x%02X", c);
        } else {
            fputc((int)c, out);
        }
        i += 1;
    }
}

static char *dup_plain(const char *s) {
    size_t len = 0;
    char *out = NULL;

    if (s == NULL) {
        s = "";
    }

    len = strlen(s);
    out = (char *)malloc(len + 1);
    if (out == NULL) {
        return NULL;
    }

    memcpy(out, s, len + 1);
    return out;
}

static char hex_digit(unsigned int v) {
    if (v < 10U) {
        return (char)('0' + v);
    }
    return (char)('A' + (v - 10U));
}

static char *dup_escaped(const char *s) {
    size_t in_len = 0;
    size_t cap = 0;
    size_t i = 0;
    size_t j = 0;
    char *out = NULL;

    if (s == NULL) {
        s = "";
    }

    in_len = strlen(s);
    cap = in_len * 4 + 1;
    out = (char *)malloc(cap);
    if (out == NULL) {
        return NULL;
    }

    while (i < in_len) {
        unsigned char c = (unsigned char)s[i];

        if (c == '\n') {
            out[j++] = '\\';
            out[j++] = 'n';
        } else if (c == '\t') {
            out[j++] = '\\';
            out[j++] = 't';
        } else if (c == '\r') {
            out[j++] = '\\';
            out[j++] = 'r';
        } else if (c == '\\') {
            out[j++] = '\\';
            out[j++] = '\\';
        } else if (c == '"') {
            out[j++] = '\\';
            out[j++] = '"';
        } else if (c < 32 || c == 127) {
            out[j++] = '\\';
            out[j++] = 'x';
            out[j++] = hex_digit((unsigned int)((c >> 4) & 0x0F));
            out[j++] = hex_digit((unsigned int)(c & 0x0F));
        } else {
            out[j++] = (char)c;
        }

        i += 1;
    }

    out[j] = '\0';
    return out;
}

static int push_token_row(token_row_t row) {
    token_row_t *new_rows = NULL;
    size_t new_cap = 0;

    if (table_rows_count == table_rows_cap) {
        new_cap = (table_rows_cap == 0) ? 64 : (table_rows_cap * 2);
        new_rows = (token_row_t *)realloc(table_rows, new_cap * sizeof(token_row_t));
        if (new_rows == NULL) {
            return 0;
        }
        table_rows = new_rows;
        table_rows_cap = new_cap;
    }

    table_rows[table_rows_count] = row;
    table_rows_count += 1;
    return 1;
}

static void flush_token_table(void) {
    size_t i = 0;
    size_t w_number = strlen("number");
    size_t w_line = strlen("line");
    size_t w_lexeme = strlen("lexeme");
    size_t w_type = strlen("type");
    size_t w_value = strlen("value");

    if (table_rows_count == 0) {
        return;
    }

    for (i = 0; i < table_rows_count; i += 1) {
        char number_buf[32];
        char line_buf[32];
        int number_len = snprintf(number_buf, sizeof(number_buf), "%d", table_rows[i].number);
        int line_len = snprintf(line_buf, sizeof(line_buf), "%d", table_rows[i].line);
        size_t lexeme_len = strlen(table_rows[i].lexeme);
        size_t type_len = strlen(table_rows[i].type_name);
        size_t value_len = strlen(table_rows[i].value);

        if (number_len > 0 && (size_t)number_len > w_number) {
            w_number = (size_t)number_len;
        }
        if (line_len > 0 && (size_t)line_len > w_line) {
            w_line = (size_t)line_len;
        }
        if (lexeme_len > w_lexeme) {
            w_lexeme = lexeme_len;
        }
        if (type_len > w_type) {
            w_type = type_len;
        }
        if (value_len > w_value) {
            w_value = value_len;
        }
    }

    printf("%-*s | %-*s | %-*s | %-*s | %-*s\n",
           (int)w_number, "number",
           (int)w_line, "line",
           (int)w_lexeme, "lexeme",
           (int)w_type, "type",
           (int)w_value, "value");

    for (i = 0; i < table_rows_count; i += 1) {
        char number_buf[32];
        char line_buf[32];

        snprintf(number_buf, sizeof(number_buf), "%d", table_rows[i].number);
        snprintf(line_buf, sizeof(line_buf), "%d", table_rows[i].line);

        printf("%-*s | %-*s | %-*s | %-*s | %-*s\n",
               (int)w_number, number_buf,
               (int)w_line, line_buf,
               (int)w_lexeme, table_rows[i].lexeme,
               (int)w_type, table_rows[i].type_name,
               (int)w_value, table_rows[i].value);

        free(table_rows[i].lexeme);
        free(table_rows[i].type_name);
        free(table_rows[i].value);
    }

    free(table_rows);
    table_rows = NULL;
    table_rows_count = 0;
    table_rows_cap = 0;
}

static void emit_token_row(const char *lexeme, const char *type_name, const char *value) {
    token_row_t row;
    char *lexeme_esc = NULL;
    char *type_copy = NULL;
    char *value_esc = NULL;

    token_index += 1;

    lexeme_esc = dup_escaped(lexeme);
    type_copy = dup_plain(type_name);
    value_esc = dup_escaped(value);

    if (lexeme_esc == NULL || type_copy == NULL || value_esc == NULL) {
        free(lexeme_esc);
        free(type_copy);
        free(value_esc);
        return;
    }

    row.number = token_index;
    row.line = token_line;
    row.lexeme = lexeme_esc;
    row.type_name = type_copy;
    row.value = value_esc;

    if (!push_token_row(row)) {
        free(lexeme_esc);
        free(type_copy);
        free(value_esc);
    }
}

static void emit_lex_error_at(int line, int col, const char *message, const char *fragment) {
    fprintf(stderr, "lexical_error %d:%d: %s", line, col, message);
    if (fragment != NULL && fragment[0] != '\0') {
        fprintf(stderr, " [");
        print_escaped(stderr, fragment);
        fprintf(stderr, "]");
    }
    fprintf(stderr, "\n");
}

static void emit_lex_error_here(const char *message, const char *fragment) {
    emit_lex_error_at(token_line, token_col, message, fragment);
}

static void string_reset(void) {
    string_lexeme_len = 0;
    string_value_len = 0;
    string_lexeme[0] = '\0';
    string_value[0] = '\0';
}

static void append_buf(char *buf, int *len, int cap, const char *src, int src_len) {
    int i = 0;
    while (i < src_len && (*len) < cap - 1) {
        buf[*len] = src[i];
        *len += 1;
        i += 1;
    }
    buf[*len] = '\0';
}

static void append_char(char *buf, int *len, int cap, char ch) {
    if (*len < cap - 1) {
        buf[*len] = ch;
        *len += 1;
        buf[*len] = '\0';
    }
}
#line 857 "scanner.yy.c"
#line 858 "scanner.yy.c"

#define INITIAL 0
#define cmt 1
#define str 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 328 "scanner.l"

#line 1077 "scanner.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 143 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 168 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 329 "scanner.l"
{
    advance_position_text(yytext, yyleng);
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 333 "scanner.l"
{
    advance_position_text(yytext, yyleng);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 337 "scanner.l"
{
    advance_position_text(yytext, yyleng);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 341 "scanner.l"
{
    advance_position_text(yytext, yyleng);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 345 "scanner.l"
{
    mark_token_start();
    comment_start_line = token_line;
    comment_start_col = token_col;
    advance_position_text(yytext, yyleng);
    BEGIN(cmt);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 353 "scanner.l"
{
    advance_position_text(yytext, yyleng);
    BEGIN(INITIAL);
}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 358 "scanner.l"
{
    advance_position_text(yytext, yyleng);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 362 "scanner.l"
{
    advance_position_text(yytext, yyleng);
}
	YY_BREAK
case YY_STATE_EOF(cmt):
#line 366 "scanner.l"
{
    emit_lex_error_at(comment_start_line, comment_start_col, "unclosed multiline comment", "/*");
    flush_token_table();
    return 0;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 372 "scanner.l"
{
    mark_token_start();
    string_start_line = token_line;
    string_start_col = token_col;
    string_reset();
    append_buf(string_lexeme, &string_lexeme_len, (int)sizeof(string_lexeme), yytext, yyleng);
    advance_position_text(yytext, yyleng);
    BEGIN(str);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 382 "scanner.l"
{
    append_buf(string_lexeme, &string_lexeme_len, (int)sizeof(string_lexeme), yytext, yyleng);
    append_buf(string_value, &string_value_len, (int)sizeof(string_value), yytext, yyleng);
    advance_position_text(yytext, yyleng);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 388 "scanner.l"
{
    append_buf(string_lexeme, &string_lexeme_len, (int)sizeof(string_lexeme), yytext, yyleng);
    if (yytext[1] == 'n') {
        append_char(string_value, &string_value_len, (int)sizeof(string_value), '\n');
    } else if (yytext[1] == 't') {
        append_char(string_value, &string_value_len, (int)sizeof(string_value), '\t');
    } else if (yytext[1] == '\\') {
        append_char(string_value, &string_value_len, (int)sizeof(string_value), '\\');
    } else if (yytext[1] == '"') {
        append_char(string_value, &string_value_len, (int)sizeof(string_value), '"');
    }
    advance_position_text(yytext, yyleng);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 402 "scanner.l"
{
    append_buf(string_lexeme, &string_lexeme_len, (int)sizeof(string_lexeme), yytext, yyleng);
    advance_position_text(yytext, yyleng);
    emit_lex_error_at(current_line, current_col - yyleng, "invalid escape sequence in string", yytext);
    append_char(string_value, &string_value_len, (int)sizeof(string_value), yytext[1]);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 409 "scanner.l"
{
    append_buf(string_lexeme, &string_lexeme_len, (int)sizeof(string_lexeme), yytext, yyleng);
    advance_position_text(yytext, yyleng);
    if (string_value_len > 32) {
        emit_lex_error_at(string_start_line, string_start_col, "string literal is longer than 32 characters", string_lexeme);
    }
    token_line = string_start_line;
    token_col = string_start_col;
    emit_token_row(string_lexeme, "STRING_LITERAL", string_value);
    BEGIN(INITIAL);
    return STRING_LITERAL;
}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 422 "scanner.l"
{
    emit_lex_error_at(string_start_line, string_start_col, "unclosed string literal", string_lexeme);
    advance_position_text(yytext, yyleng);
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(str):
#line 428 "scanner.l"
{
    emit_lex_error_at(string_start_line, string_start_col, "unclosed string literal", string_lexeme);
    flush_token_table();
    return 0;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 434 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "KW_BEGIN", yytext);
    return KW_BEGIN;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 441 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "KW_END", yytext);
    return KW_END;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 448 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "KW_IF", yytext);
    return KW_IF;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 455 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "KW_ELSE", yytext);
    return KW_ELSE;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 462 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "KW_WHILE", yytext);
    return KW_WHILE;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 469 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "KW_FOR", yytext);
    return KW_FOR;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 476 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "KW_DO", yytext);
    return KW_DO;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 483 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "KW_PRINT", yytext);
    return KW_PRINT;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 490 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "KW_READ", yytext);
    return KW_READ;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 497 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "KW_INT", yytext);
    return KW_INT;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 504 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "KW_FLOAT", yytext);
    return KW_FLOAT;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 511 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "KW_STRING", yytext);
    return KW_STRING;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 518 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "KW_BOOL", yytext);
    return KW_BOOL;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 525 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "KW_RETURN", yytext);
    return KW_RETURN;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 532 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "KW_VAR", yytext);
    return KW_VAR;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 539 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "KW_THEN", yytext);
    return KW_THEN;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 546 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "KW_STEP", yytext);
    return KW_STEP;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 553 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "KW_TO", yytext);
    return KW_TO;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 560 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "BOOL_LITERAL", "true");
    return BOOL_LITERAL;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 567 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "BOOL_LITERAL", "false");
    return BOOL_LITERAL;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 574 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "LAND", yytext);
    return LAND;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 581 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "LOR", yytext);
    return LOR;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 588 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "LNOT", yytext);
    return LNOT;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 595 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_lex_error_here("invalid float literal", yytext);
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 601 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_lex_error_here("invalid float literal", yytext);
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 607 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_lex_error_here("invalid float literal", yytext);
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 613 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "FLOAT_LITERAL", yytext);
    return FLOAT_LITERAL;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 620 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "INT_LITERAL", yytext);
    return INT_LITERAL;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 627 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    if ((int)strlen(yytext) > 32) {
        emit_lex_error_here("identifier is longer than 32 characters", yytext);
    }
    emit_token_row(yytext, "IDENTIFIER", yytext);
    return IDENTIFIER;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 637 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "COLON_ASSIGN", yytext);
    return COLON_ASSIGN;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 644 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "EQ", yytext);
    return EQ;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 651 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "NEQ", yytext);
    return NEQ;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 658 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "LE", yytext);
    return LE;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 665 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "GE", yytext);
    return GE;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 672 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "LAND", yytext);
    return LAND;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 679 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "LOR", yytext);
    return LOR;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 686 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "ASSIGN", yytext);
    return ASSIGN;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 693 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "PLUS", yytext);
    return PLUS;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 700 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "MINUS", yytext);
    return MINUS;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 707 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "MUL", yytext);
    return MUL;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 714 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "DIV", yytext);
    return DIV;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 721 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "MOD", yytext);
    return MOD;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 728 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "LT", yytext);
    return LT;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 735 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "GT", yytext);
    return GT;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 742 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "LNOT", yytext);
    return LNOT;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 749 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "SEMICOLON", yytext);
    return SEMICOLON;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 756 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "COMMA", yytext);
    return COMMA;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 763 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "COLON", yytext);
    return COLON;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 770 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "DOT", yytext);
    return DOT;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 777 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "LPAREN", yytext);
    return LPAREN;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 784 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "RPAREN", yytext);
    return RPAREN;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 791 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "LBRACE", yytext);
    return LBRACE;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 798 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "RBRACE", yytext);
    return RBRACE;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 805 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "LBRACKET", yytext);
    return LBRACKET;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 812 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_token_row(yytext, "RBRACKET", yytext);
    return RBRACKET;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 819 "scanner.l"
{
    mark_token_start();
    advance_position_text(yytext, yyleng);
    emit_lex_error_here("invalid symbol", yytext);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 825 "scanner.l"
{
    flush_token_table();
    return 0;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 829 "scanner.l"
ECHO;
	YY_BREAK
#line 1859 "scanner.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 143 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 143 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 142);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 829 "scanner.l"


